_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: StandupMonkey
  description: A slack bot to conduct standups & generate reports.
  background_color: "#8046b3"
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: StandupMonkey
    always_online: true
  slash_commands:
    - command: /standup
      url: https://standup-monkey.herokuapp.com/slack/events
      description: Asks for standup status
      should_escape: false
    - command: /generate-report
      url: https://standup-monkey.herokuapp.com/slack/events
      description: Generate report for given user
      should_escape: true
oauth_config:
  redirect_urls:
    - https://standup-monkey.herokuapp.com/slack/oauth_redirect
  scopes:
    bot:
      - channels:history
      - chat:write
      - commands
      - files:write
      - im:history
      - im:read
settings:
  event_subscriptions:
    request_url: https://standup-monkey.herokuapp.com/slack/events
    bot_events:
      - message.channels
      - message.im
  interactivity:
    is_enabled: true
    request_url: https://standup-monkey.herokuapp.com/slack/events
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
